### ISSUE TITLE
Panneau Extruder

### ISSUE THREAD

**Issue by HollowerMan** [pollenam/DuetWebControl#10]
On a une notion de "tool actif" qui existe dans Duet WebControl 
- On peut sélectionner le tool en cliquant dessus dans le status des pages legacy
- On envoie T1 à la sélection du tool 1 (TX pour le tool X)
- On envoie T-1 si on déselectionne

=> On a le même comportement que le panneau "Tools" existant

Extrusion/Retract Inifini : on envoie une macro pour l'instant avec paramêtre T1/T2/T3/T4

Mixer : Extrusion Factor Panneau Status 1/(2*NBEXT) - 1 (Tous les impairs)
Extrusion Factor : Extrusion Factor Panneau Status 0/(2*NBEXT) - 1 (Tous les pairs)

PID Set: On liste les macros dans le dossier "macros/pid", et on appelle la macro qui va bien avec en paramètre T1/T2/T3/T4. Par défaut on affiche le premier

Voir si on peut accéder au filesystem pour maintenir les états de la machine.

**Comment by HollowerMan** [comment]
La vitesse d'extrusion infinie va de 0.4tr/min à 12tr/min ou +. On utilise le même systeme que les extrusion factor avec un slider qui peut aller à plus une fois que tu as séletionné une grosse option

**Comment by guillaumeterral** [comment]
- [x] vérifier le step de l'extrustion speed il doit etre de 0.1 et le max est mouvant (10% de + que valeur actuel) 


- [x] Extrusion factor et mixer avec les pair/impair

- [x] macro pour infinte extrusion (on stock la dernier commande envoyé dans notre cache pour avoir le statut)

Quand on clique sur extrude:
--> Extruding 
--> envoi macro avec RPM 
QUand on reclick dessus 
--> Renvoi un macro de stop. 

- [x] Rajouter une action quand on clique sur l'état, s'inspirer du comportement existant (fault = popup etc...)

**Comment by guillaumeterral** [comment]
Salut @MasterHugsy,

Nous avions noté lors d'une précédente discussion un sujet à propos de la sécurité des températures d'extrusion, est ce que ce sujet est toujours d'actualité et si oui peux tu me donner plus d'info ?

Merci

**Comment by guillaumeterral** [comment]
Salut @MasterHugsy 
Dans la dernière version il y a l'implémentation de l'extrusion infini si tu peux tester et me dire si cela fonctionne ? 
Petite addition, dans le pannel General, il y a un lien en haut à coté de diagnostics pour télécharger les logs.
Merci

**Comment by MasterHugsy** [comment]
> Salut @MasterHugsy,
> 
> Nous avions noté lors d'une précédente discussion un sujet à propos de la sécurité des températures d'extrusion, est ce que ce sujet est toujours d'actualité et si oui peux tu me donner plus d'info ?
> 
> Merci

Normalement non, on est entrain de bosser dessus côté firmware 

> Salut @MasterHugsy
> Dans la dernière version il y a l'implémentation de l'extrusion infini si tu peux tester et me dire si cela fonctionne ?
> Petite addition, dans le pannel General, il y a un lien en haut à coté de diagnostics pour télécharger les logs.
> Merci

Super je teste ça la semaine pro
