### ISSUE TITLE
Arrows mask the temperature 

### ISSUE THREAD

**Issue by MasterHugsy** [pollenam/DuetWebControl#14]
Arrow mask the temperatures
![image](https://user-images.githubusercontent.com/92175415/189906267-8c43750f-f987-4023-81fe-aae345dfb433.png)

**Comment by MasterHugsy** [comment]
only applies when the temperature is a 3 digit number

**Comment by guillaumeterral** [comment]
Salut @MasterHugsy  
J'ai avancé sur l'écran de calibration mais j'ai quelques questions, tu trouveras ci joint un screenshot de l'écran. 
![image](https://user-images.githubusercontent.com/3050726/189930549-4df3b200-ca92-43c1-8a1b-3baba1607014.png)

Mes questions sont: 
- Quel est le nom de la macro à appeler avec le boutton create.
- Comment récupérer les valeurs initial de la partie parameters ?
- Dans le photoshop pour la partie parameters il y a 2 autre boutton : Cancel et Refresh quel est le comportement attendu ? 

Merci

**Comment by MasterHugsy** [comment]
Les réponses :
- M98 P"/macros/HONEYPRINT/Compensation_Start"
- Normalement il faudrait aller lire dans le fichier /sys/config-override.g mais si tu veux tu peux te créer des champs dans le fichier tampon.
- Cancel remet les valeurs par défaut et refresh va lire /sys/config-override.g je pense

**Comment by MasterHugsy** [comment]
D'ailleurs vous avez une liste de macros que vous pouvez utiliser 
![image](https://user-images.githubusercontent.com/92175415/189956819-dece115f-a6d4-4347-a530-3171792d5e23.png)

; example for probe offset update: M98 P"/macros/HONEYPRINT/Probe_Offset_Save" K0 X0 Y0 Z32.25
; example for tool offset update : M98 P"/macros/HONEYPRINT/Tool_Offset_Save" T1 X-8.89 Y-13.31 Z-0.5 
; Exemple for setting PID : M98 P"/macros/HONEYPRINT/Set_PID" P1 T1 ; sets PID 1 to T1 extruder

Set Temp est totallement optionelle 
; example for tool set temp : M98 P"/macros/HONEYPRINT/Set_Temp" T1 C65 E110 H140
; example for radiant set temp : M98 P"/macros/HONEYPRINT/Set_Temp" R110
; example for heating chamber set temp : M98 P"/macros/HONEYPRINT/Set_Temp" G50
; example for bed set temp : M98 P"/macros/HONEYPRINT/Set_Temp" B90

**Comment by guillaumeterral** [comment]
> Les réponses :
> 
> * M98 P"/macros/HONEYPRINT/Compensation_Start"
> * Normalement il faudrait aller lire dans le fichier /sys/config-override.g mais si tu veux tu peux te créer des champs dans le fichier tampon.
> * Cancel remet les valeurs par défaut et refresh va lire /sys/config-override.g je pense

Ok, juste pour ma culture perso quand on va exécuter la macro pour set les offset, cela va impacter le fichier config-override.g ? 

Si je change les valeurs dans la UI et que je save et ensuite je fais un refresh je devrais garder les mêmes infos c'est ca ?

**Comment by MasterHugsy** [comment]
- Exactement, la macro fait un G10 avec les valeurs des offsets et un M500 qui vient écrire le fichier config-override.g
- Oui, après la méthode c'est au choix, soit en allant regarder un fichier tampon soit en allant lire les valeurs [tools[].offsets[]](https://github.com/Duet3D/RepRapFirmware/wiki/Object-Model-Documentation#toolsoffsets)

**Comment by guillaumeterral** [comment]
> only applies when the temperature is a 3 digit number

Done

**Comment by guillaumeterral** [comment]
Salut @MasterHugsy 
J'ai finis l'implémentation de l'écran de calibration (sauf le create, a tu le nom de la macro a utiliser ?), Si tu veux commencer à tester et me faire des retours si besoin. 
G.

**Comment by guillaumeterral** [comment]
s

**Comment by guillaumeterral** [comment]
@MasterHugsy Nous avons une question par rapport au Set PID.
Nous stockons dans notre cache la dernière macro SET PID exécuté,
Mais au redémarrage de la machine cette dernière n'est pas exécuté j'imagine mais nous affichons dans la UI la dernière exécuté.
Est ce un comportement attendu ?

**Comment by MasterHugsy** [comment]
Oui effectivement, les PID fonctionnent comme les offsets, ils sont stockés dans config-override.g

**Comment by MasterHugsy** [comment]
> Salut @MasterHugsy J'ai finis l'implémentation de l'écran de calibration (sauf le create, a tu le nom de la macro a utiliser ?), Si tu veux commencer à tester et me faire des retours si besoin. G.

C'est M98 P"/macros/HONEYPRINT/Compensation_Start" pour créer une nouvelle map

Je compile et je test l'interface dès aujoud'hui
