### ISSUE TITLE
Scroll vers le bas dans la vue de la calibration scroll également la page web

### ISSUE THREAD

**Issue by MasterHugsy** [pollenam/DuetWebControl#16]
Lorsque l'on défile la page avec la souris sur la vue du plateau dans la page de calibration, cela dé-zoom la vue mais défile également la page web (ce sui n'est pas souhaité)

**Comment by guillaumeterral** [comment]
Salut @MasterHugsy ,
Sur windows avec une souris je n'ai pas ce comportement, peux tu me dire quel navigateur/OS souris/Trackpad tu utilises ?

merci, 

Guillaume

**Comment by MasterHugsy** [comment]
Windows et MacOS ont ce problème souris avec scroll wheel et sur MacOS un trackpad classique.
C'est bizarre que ce soucis n'existe que de mon côté

**Comment by guillaumeterral** [comment]
Salut @MasterHugsy  Nous avons remarqué que si tu scroll sur la bar de scale (sur la droite) oui cela scroll mais c'est un comportement attendu et existant dans l'ancien plugin par contre si tu scroll au centre de la vue 3D nous n'avons pas le problème, ni moi ni philippe en testant sur Mac ou Windows , trackpad ou souris.

**Comment by MasterHugsy** [comment]
Salut @guillaumeterral , je vais re-compiler la semaine prochaine ça me semble bizarre que ça soit isolé de mon côté.
