### ISSUE TITLE
Les coordonnées affichées dans la section "Build Surface" du "Dashboard" son celles de la machine et non du tool.

### ISSUE THREAD

**Issue by MasterHugsy** [pollenam/DuetWebControl#17]
![image](https://user-images.githubusercontent.com/92175415/190441053-10327246-da34-4ee0-93b1-c7562f2cb8b4.png)
On souhaite que ces coordonnées soient celles du tool (qui a des offsets) et non de la machine, exactement comme dans l'interface DWC
![image](https://user-images.githubusercontent.com/92175415/190441500-4f147a68-d0c8-49ee-96d2-826ba924940e.png)
La position n'a pas changé entre les deux captures d'écran

Merci !
Hugues

**Comment by guillaumeterral** [comment]
Fixed
