### ISSUE TITLE
Écran "Dashboard"

### ISSUE THREAD

**Issue by HollowerMan** [pollenam/DuetWebControl#2]
Création du dashboard spécifique Pollen

* Extrusion infinie => Comment gere-t-on l’extrusion infinie ?
* Gestion securité temperature d’extrusion ?
* ATTENTION => bouton calibration = declenche macro (compensation find)
  * on desactive le bouton en impression
* Vérifier que le bouton homing est bien grisé pendant une impression

**Comment by guillaumeterral** [comment]
cacher les autres axes que X Y Z
