### ISSUE TITLE
Z limit 

### ISSUE THREAD

**Issue by guillaumeterral** [pollenam/DuetWebControl#20]
Salut @MasterHugsy 
Dans le panel Build surface nous avons un switch Z limit 
![image](https://user-images.githubusercontent.com/3050726/190608456-70bef6d3-6737-439b-a069-071661d6cf9b.png)

Qu'est ce qui doit être plug comme fonctionnalité derrière ?

**Comment by MasterHugsy** [comment]
M98 P"/macros/HONEYPRINT/Z_Limits" S0 pour retirer les limites
M98 P"/macros/HONEYPRINT/Z_Limits" S1 pour activer les limites

En général si vous avez besoin d'une fonctionnalité vous pouvez directement choisir un nom de macro et des paramètres si besoin. Dans ce cas le nom est "Z_Limits" et le paramètre est S (plusieurs paramètres sont possibles)

**Comment by HollowerMan** [comment]
Fixed by f8c554df64292608ac5ed05d3dd77b8d945d8022
