### ISSUE TITLE
Extrusion infinie

### ISSUE THREAD

**Issue by HollowerMan** [pollenam/DuetWebControl#21]
On change de principe pour l'extrusion infinie :

@masterhugsy

- [x] Valider la macro select multitool
- [x] Connaitre le ratio entre vitesse RPM et valeur d’extrusion factor
- [x] Tester les extrusion factor négatifs
- [x] quelle est la commande et quelle est l’interval de temps ?
  - [x] valider que les extrudeurs extrudent bien pendant le même temps mais à des vitesses différentes 
- [x] valider qu’on peut intercaler des commandes autres entre ces instructions d'extrusion toutes les XX secondes
- [x] valider le principe de fonctionnement complet avant implementation dans Honeyprint

**Ensuite implementation côté HoneyPrint** 
Lorsque l'extrusion/retract infini démarre (ou est modifiée cad on demarre/arrete un ext alors qu’un ext est en train d’extruder)
    - on envoie le commande M98 “/macros/SELECT/Select TX” (ou X = 12 pour T1 + T2 ou par ex 14 pour T1 + T4 ou T124 pour T1 + T2 + T4)
    - on désactive les champs extrusion factor des extrudeurs en question dans l’interface
    - on envoie la macro pour modifier les extrusion factor
    - valider qu’on peut envoyer un extrusion factor negatif pour gérer le retract
    - à partir de là tant qu’on a au moins un bouton d’un extrudeur en mode extude/retract, honeyprint envoie une commande “G1 EX FX” toutes les XX secondes
    - lorsque ca s’arrete on remet les extrusion factor à la bonne valeur (celle du slider) et on arete d’envoyer les commandes
    - FIXME HUGUES valider qu’on peut intercaler des commandes autres entre ces instructions dextrusion toutes les XX secondes

**Comment by MasterHugsy** [comment]
Yop, it's good news time: @HollowerMan @VictorPollen 

- La macro select multitool fonctionne mais j'ai encore quelques tests à réaliser dessus
- La commande d'extrusion à envoyer : G1 E5 F20 (durée 15s)
- Si X = Y dans G1 E(X) F(Y) alors la commande aura une durée de exactement 1 min, diviser exactement X par 2 revient à extruder 2 fois moins donc la commande aura une durée 2 fois moins longue donc 30s. G1 E5 F20 extrude 5mm à 20mm/min donc elle dure 15s exactement
- Extruder avec G1 E5 F20 fait donc une extrusion de 15s, changer les mixing ratio avec M567 ne change pas la durée de l'extrusion
- Un mixing ratio négatif rétracte
- On peut intercaler des commandes entre des G1 EXX FXX tout en restant fluide
- RPM = 10x F(speed) OU F(speed) = 0.1 x RPM /// G1 E10 fait 1 tour de roue, si on met F10 alors c'est 1 tour en 1 minute
- M98 P"/macros/SELECT/Select" TXXXX arrive à s'intercaler entre des G1 E5 F20 
- Mettre des mixings ratios différents entre les extrudeurs avec M567 n'affecte pas la durée de l'extrusion G1 E5 F20

Pour l'instant tout est ok pour lancer l'implémentation HoneyPrint, il me reste :
- Faire une macro qui assigne correctement les différentes vitesses d'extrusion aux extrudeurs 
- Comprendre pourquoi les sliders "extrusion factor" n'affectent pas la vitesse d'extrusion et que seul M567 y arrive
- Terminer de valider la macro select (multitool compris)

**Comment by HollowerMan** [comment]
OK, on commence l'implementation de notre côté lorsqu'on aura fini le reste des points des autres points.
On peut faire un point de vive voix (même rapide) lorsque tu as validé les trois derniers points ?

**Comment by MasterHugsy** [comment]
Yes, je te dis mais je pense que éventuellement demain c'est bon

**Comment by MasterHugsy** [comment]
La commande qui setup les vitesses d'extrusion fonctionne
Ex : M98 P"/macros/HONEYPRINT/Set_Extrusion_Rate" A1.2 B1.4 C2.4 C1.0
A set la vitesse d'extrusion de T1, ici 1.2 RPM
B set la vitesse d'extrusion de T2, ici 1.4 RPM
C set la vitesse d'extrusion de T3, ici 2.4 RPM
D set la vitesse d'extrusion de T4, ici 1.0 RPM

**Comment by guillaumeterral** [comment]
Salut @MasterHugsy 

j'ai push sur la branche l'implémentation de l'"extrusion infini et dans le repo RepRapFirmware sous le commit: https://github.com/pollenam/RepRapFirmware/commit/9f1137d0d544e7dfedc4d759adbc32b08c9f5957

un update du firmaware. 

Pour le moment la commande G1 E5 F20  est hardcodé, on peut avec pas trop de dev en plus customizé ces valeurs si nécéssaires.

Guillaume

**Comment by MasterHugsy** [comment]
Il manque des \" dans certaines commandes, du coup les exécutions ne marchent pas toutes
également, pourquoi T41? Je n'ai pas sélectionné de T4
![image](https://user-images.githubusercontent.com/92175415/193537494-6ba480bb-3cf1-4fb1-9fec-14d09c84f0b1.png)

**Comment by MasterHugsy** [comment]
Concernant le firmware, est-ce que c'est possible de commencer par un délais de par exemple 1100 puis d'avoir tous les délais qui suivent à 1000? On a un léger problème où les commandes s'accumulent plus vite que les délais ce qui fait que la réactivité du système n'est pas top plus on extrude

**Comment by guillaumeterral** [comment]
Salut dans l'idée oui ca doit être possible mais j'ai peur que si on est un timing pile poile genre 1000ms pour une extrude qui dure 1000ms ca risque de couper, on peut réfléchir à la bonne manière de faire. 
On va regarder ça, de ton coté tu as eu d'autres soucis ?

**Comment by MasterHugsy** [comment]
Justement si le premier délais est de 1100 par exemple, puis de 1000 on aura toujours 100 de décalage ce qui est bien. Si on fait 1100 sur une extrusion de 1000ms le délais sera de 100 puis 200 puis 300...etc....( du coup quand tu arrêtes ton extrusion ça met longtemps à s'arrêter)
Sinon j'ai pas eu d'autres soucis c'est top

**Comment by guillaumeterral** [comment]
Ok, je regarde de suite et je t'envoie une version, par contre est ce que la commande est toujours :
        httpInput->Put(HttpMessage, "G1 E5 F20");
Ou c'est d'autres valeurs ?

**Comment by MasterHugsy** [comment]
Je suis descendu à G1 E1 F60 donc avec un délai normal de 1s et premier délai à 1,1s

**Comment by guillaumeterral** [comment]
@MasterHugsy  J'ai push sur la branch firmware l'update de 1.1s puis 1s.
G.

**Comment by MasterHugsy** [comment]
̶B̶o̶n̶,̶ ̶c̶'̶e̶s̶t̶ ̶t̶o̶u̶j̶o̶u̶r̶s̶ ̶b̶i̶z̶a̶r̶r̶e̶.̶ ̶J̶'̶a̶i̶ ̶l̶'̶i̶m̶p̶r̶e̶s̶s̶i̶o̶n̶ ̶q̶u̶'̶o̶n̶ ̶e̶s̶t̶ ̶l̶i̶m̶i̶t̶é̶ ̶p̶a̶r̶ ̶l̶e̶ ̶p̶o̶r̶t̶T̶I̶C̶K̶_̶P̶E̶R̶I̶O̶D̶_̶M̶S̶ ̶c̶a̶r̶ ̶l̶e̶ ̶d̶é̶l̶a̶i̶ ̶a̶ ̶l̶'̶a̶i̶r̶ ̶d̶'̶ê̶t̶r̶e̶ ̶a̶r̶r̶o̶n̶d̶i̶ ̶
Ok alors un délais de 100 puis 2000 avec G1 E2 F60 a l'air de marcher (ça ne fait que 1 micro délais après la première extrusion), je cherche à comprendre pourquoi
