### ISSUE TITLE
Réunion du 22 Sept 2022 

### ISSUE THREAD

**Issue by MasterHugsy** [pollenam/DuetWebControl#22]
- Force le mode actif sur un extrudeur lorsque l'on change d'extrudeur et également quand l'utilisateur clique sur "actif" (si on clique sur actif, alors on passe en off directement), à aucun moment on ne doit avoir une chauffe en mode standby
- Print again qui ne fait rien après un emergency stop
- Bouton reset sur les sliders
- Clic droit et start dans "g-codes files" ne marche pas
- Set PID à appliquer à tous les extrudeurs

**Comment by HollowerMan** [comment]
Voici la liste des éléments à corriger que j'ai noté :


### Général
- [x] Ajouter un “reset” sur tous les sliders, un peu comme les extruder factors dans status legacy
- [x] Vérifier que les nouvelles couleurs sont bien appliquées à tous les lsiders (idem rpm sur l’extruder panel)
- [x] Avoir une animation d’affichage pour la console
- [x] Avoir la même couleur pour le texte/icon noir dans les boutons standards que le noir/marron de la sidebar

### Dashboard

- [x] Panel extruder
  - [x] Lorsqu’on change d’extruder sélectionné, les points de chauffe de l’extruder qu’on vient de déslectionner passent en mode “standby”
    - [ ] Forcer à rester (ou repasser) en mode actif
    - [x] Empecher les heaters de passer en mode “standby” voir https://docs.duet3d.com/User_manual/Reference/Gcodes#m568-set-tool-settings
  - [x] Combobox devrait etre “shrinkable” dans le titre pour que ce soit toujours sur la même ligne
- [x] Au démarrage de la machine, il faut forcer les extrusion status à stopped
- [x] Apres un emergency stop, on a toujours “Print again” mais il ne fait rien
- [x] Build surface -> panel a revoir avec le responsive



### Gcode Files

- [x] clic droit -> imprimer ne lance pas l’impression

### Settings

- [x] Section network avec “Set IP Address” (0.0.0.0 étant DHCP)

### Calibration

- [x] avoir le canvas avec la même hauteur que son panel sur sa droite

### I18n

- [x] Stop/Extrude/Retract extruder panel

**Comment by HollowerMan** [comment]
OK pour closer ?
