### ISSUE TITLE
Ne pas afficher les tools 5 à 15 

### ISSUE THREAD

**Issue by MasterHugsy** [pollenam/DuetWebControl#23]
Les tools 5 à 15 sont réservés à la multi extrusion, seuls les tools 1 à 4 doivent être affichés

**Comment by HollowerMan** [comment]
Tu as un screenshot de ce problème ? Tu as plus de 4 extrudeurs ?

**Comment by MasterHugsy** [comment]
![image](https://user-images.githubusercontent.com/92175415/192268760-be3460cd-8474-470a-b577-2941776c2296.png)
Eh oui, pour les tools qui mixent les moteurs d'extrusion pour la multi extrusion
