### ISSUE TITLE
Écran "Calibration"

### ISSUE THREAD

**Issue by HollowerMan** [pollenam/DuetWebControl#3]
* mix entre la presentation plus ou moins avec le systeme de heightmaps
* on garde la partie parameters, ca déclanche une macro avec les 12 paramètres
* on utilise config-override.g pour lire les infos a mettre dans l’interface (pour les offsets x/y/z)

**Comment by HollowerMan** [comment]
calibration = on prends toutes les heightmpa qu’on affiche en liste
pour apply on renomme en heightmap.csv + “G29 S1”
Pour en créer une nouvelle, on lance la macro comensation
on garde la 3d + les “statistics”

Section Parameters

On garde les champs du Photoshop, et le save envoie la commande 

    M98 P"/macros/HONEYPRINT/Tool_Offset_Save" T1 X-8 Y-13 Z-0.5

Restore default = X/Y OK sur photoshop, et Z à 40 par ex.

**Comment by guillaumeterral** [comment]
- [ ] reste la macro create a implémenter.
- [ ] CSS pour create compensation

**Comment by guillaumeterral** [comment]
@MasterHugsy Quels sont les paramètres de la macro /macros/HONEYPRINT/Compensation_Start , dans la UI j'ai S_Count etc..
Sous quels format je dois les passer ?

**Comment by HollowerMan** [comment]
@VictorPollen On avait défini qu'on voulait modifier le layout de ce panel (voir screenshot). Te souviens-tu de ce qu'on avait défini ?

![Attachment](https://user-images.githubusercontent.com/3944454/190609215-7a6a248a-9fc5-4d4e-b53a-bc31401920ac.jpeg)

**Comment by VictorPollen** [comment]
Hello, voici une capture du panel "calibration" souhaité.

![Ecran-calibration-SX2](https://user-images.githubusercontent.com/55436276/191039430-ef055dda-778d-4a1b-a32b-bd3008517f2e.jpg)
