### ISSUE TITLE
Gestion des autorisations

### ISSUE THREAD

**Issue by HollowerMan** [pollenam/DuetWebControl#4]
mot de passe de la machine : hash de son prenom et/ou de son numero pam type pam-200XX
	=> dans config.g

**Comment by guillaumeterral** [comment]
Create new settings component with:
- License
- Language
- Password to activate legacy Mode

**Comment by guillaumeterral** [comment]
10 first char of MD5 of machine name

**Comment by HollowerMan** [comment]
https://docs.google.com/spreadsheets/d/1lA6d0h7f42_MXAF35rBV2KeHca824hti1zGLdojl8T4/edit#gid=0
